[DEV-7977] Add additional columns for Scatter plot tooltips
CDCgov/cdc-open-viz pull request #1311
Opened 2024-05-29 18:00 UTC by Atash3000

2024-05-30 19:24 UTC, adamdoe requested changes

2024-05-30 19:24 UTC, adamdoe commented on packages/chart/src/components/ScatterPlot/ScatterPlot.jsx
> +  // tooltips for additional columns
const

2024-05-30 19:24 UTC, adamdoe commented on packages/chart/src/components/ScatterPlot/ScatterPlot.jsx
>    let circleRadii = 4.5
const

2024-06-03 14:58 UTC, mpallansch approved these changes

2024-06-03 14:59 UTC, mpallansch approved these changes

2024-06-03 14:59 UTC, merged