[DEV-7953] Hide first grid lines when axis is off
CDCgov/cdc-open-viz pull request #1333
Opened 2024-06-06 20:53 UTC by Atash3000

2024-06-10 17:42 UTC, adamdoe approved these changes

2024-06-10 17:42 UTC, adamdoe approved these changes

2024-06-10 17:44 UTC, adamdoe commented
<img width="622" alt="Screen Shot 2024-06-10 at 10 43 21 AM" src="https://github.com/CDCgov/cdc-open-viz/assets/17502761/7e774b87-92a8-4b94-b212-877434b9f226">
@Atash3000 I'm still seeing the grid lines when axis is off.

2024-06-10 17:44 UTC, adamdoe requested changes
See image

2024-06-12 15:31 UTC, Atash3000 commented
The commit is wrong, so we need to show first grid line when axis is off and hide grid when axis is on

2024-06-12 16:31 UTC, merged