no lerna required
CDCgov/cdc-open-viz pull request #1419
Opened 2024-07-22 18:57 UTC by joshlacey

Gives us the ability to use yarn for everything we are using lerna for. 

Examples: 

`lerna run build` -> `yarn workspaces run build`

`lerna run --scope @cdc/editor start` -> `yarn workspace @cdc/editor run start`

2024-07-25 17:15 UTC, adamdoe requested changes
Can you add the commands needed for versioning and publishing to npm/github that `lerna publish` uses? If we're removing lerna from being used we should also remove that package as a dependency.

2024-08-02 16:26 UTC, joshlacey commented
I think all the lerna publish and version was doing is running npm under the hood. I'm having trouble really understanding what the difference would be because learna publish isn't working for me.

2024-08-06 16:25 UTC, adamdoe commented
I think I'd like to see an interactive way of tagging the packages and publishing them to npm/git with yarn before removing lerna. When useWorkspaces is set to true in lerna.json that functionality is possible with lerna publish.

2024-08-21 16:49 UTC, adamdoe commented
Closing until we have solutions for versioning/publishing/tagging that provide similar functionality to lerna publish.

2024-08-21 16:49 UTC, closed without merging