Feature/dev 4215f
CDCgov/cdc-open-viz pull request #1422
Opened 2024-07-23 16:36 UTC by Atash3000

2024-07-23 18:43 UTC, adamdoe commented
@Atash3000 can you assign a milestone for this PR?

2024-07-25 17:32 UTC, adamdoe requested changes
Hey @atash3000, I didn't test this through the editor yet. Can you go through the first iteration of feedback and re-request a review when finished? Thanks!

2024-07-25 17:32 UTC, adamdoe commented on packages/chart/src/components/EditorPanel/EditorPanel.tsx
> +                      {visHasBrushChart() && (
Good!

2024-07-25 17:32 UTC, adamdoe commented on packages/chart/src/components/EditorPanel/useEditorPermissions.js
> +    if (config.xAxis.type === 'categorical') return false
Good!

2024-07-31 13:19 UTC, Atash3000 commented on packages/chart/src/components/BrushChart.tsx
> +function BrushChart({ xMax, yMax, xScaleBrush: x }) {
Resolved.

2024-07-31 13:21 UTC, Atash3000 commented on packages/chart/src/components/BrushChart.tsx
> +  const textWidth = getTextWidth(tooltipText, `normal ${16 / 1.1}px sans-serif`)
fixed

2024-07-31 13:22 UTC, Atash3000 commented on packages/chart/src/components/BrushChart.tsx
> +    return Number(yMax) + config.xAxis.axisBBox + brushheight * 1.5
fixed

2024-07-31 13:22 UTC, Atash3000 commented on packages/chart/src/components/BrushChart.tsx
> +    const textWidth = getTextWidth(firstDate, `normal ${16 / 1.1}px sans-serif`)
fixed

2024-07-31 13:22 UTC, Atash3000 commented on packages/chart/src/components/BrushChart.tsx
> +        const rightHandlePath = 'M6.5,10A6,6 0 0 0 0.5,16V14A6,6 0 0 0 6.5,20ZM4.5,18V12M2.5,18V12'
fixed

2024-07-31 17:46 UTC, Atash3000 commented on packages/chart/src/components/BrushChart.tsx
> +  const { tableData, config, parseDate, setBrushConfig, getTextWidth } = useContext(ConfigContext)
fixed

2024-07-31 17:46 UTC, Atash3000 commented on packages/chart/src/components/BrushChart.tsx
> +import { scaleTime } from '@visx/scale'
fixed

2024-07-31 17:46 UTC, Atash3000 commented on packages/chart/src/components/BrushChart.tsx
> +    const safeInvert = (xScale, value) => {
Fixed

2024-08-07 16:01 UTC, merged