Feature/dev 9146
CDCgov/cdc-open-viz pull request #1548
Opened 2024-09-26 17:10 UTC by Atash3000

## [Replace With Ticket Number]
Fixed spacing on message, filters and legend (when legend if top)
October sprint.

## Testing Steps

## Self Review

- I have added testing steps for reviewers
- I have commented my code, particularly in hard-to-understand areas
- My changes generate no new warnings
- New and existing unit tests are passing

## Screenshots (if applicable)

## Additional Notes

2024-10-04 19:04 UTC, adamdoe requested changes

2024-10-04 19:04 UTC, adamdoe commented on packages/core/styles/filters.scss
> +    label {
fix: can we try using bootstraps font classes here and remove the class?

`fw-bolder`, `fs-6`, `mb-[number]` maybe?

2024-10-04 19:04 UTC, adamdoe commented on packages/core/styles/_global.scss
> -  &.legend_visible_top {
good!

2024-10-07 17:06 UTC, joshlacey requested changes

2024-10-07 17:06 UTC, joshlacey commented on packages/core/components/Filters.tsx
> +  const getCLasses = () => {
getClasses

2024-10-07 17:06 UTC, joshlacey commented on packages/core/components/Filters.tsx
> +      type === 'map' ? general.headerColor : visualizationConfig?.visualizationType === 'Spark Line' ? null : theme
return empty string here  so that null doesn't get interpolated into the classname

2024-10-07 17:59 UTC, Atash3000 commented on packages/core/components/Filters.tsx
> +  const getCLasses = () => {
Fixed!

2024-10-10 16:45 UTC, mpallansch approved these changes

2024-10-10 16:57 UTC, merged