Feature/dev 9734a
CDCgov/cdc-open-viz pull request #1812
Opened 2024-12-31 16:28 UTC by Atash3000

## [Replace With Ticket Number]

## Testing Steps
Refactored code

## Self Review

- I have added testing steps for reviewers
- I have commented my code, particularly in hard-to-understand areas
- My changes generate no new warnings
- New and existing unit tests are passing

## Screenshots (if applicable)

## Additional Notes

2025-01-03 19:44 UTC, adamdoe requested changes

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/CdcChartComponent.tsx
> +      console.log(currentData, 'currentDatacurrentData')
Remove

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/CdcChartComponent.tsx
> +    setConfig(newConfig)
If you're setting the config using a dispatch action shouldn't this be removed?

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/CdcChartComponent.tsx
> +        setFilteredData(filteredData)
Should this use dispatch()?

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/CdcChartComponent.tsx
>        setLoading(false)
Should this use a dispatch fn, ie SET_LOADING?

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/CdcChartComponent.tsx
> +  console.log(filteredData, 'filteredData')
Remove

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/ConfigContext.tsx
> +export const ChartdDispatchContext = createContext<Dispatch<ChartActions>>(() => {})
Spelling

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/components/BrushChart.tsx
> +import { ChartdDispatchContext } from '../ConfigContext'
Spelling

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/store/chart.actions.ts
> +import { DimensionsType } from '@cdc/core/types/Dimensions'
Nicely done 🙌

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/CdcChartComponent.tsx
> -  hostname,
Good, verified unused.

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/CdcChartComponent.tsx
> +  console.log(data, 'data')
Remove

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/CdcChartComponent.tsx
> -  configUrl,
How are we loading the configs from here? I'm not seeing this included in the loadConfig section.

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/CdcChartComponent.tsx
> +        setFilteredData(filteredData)
dispatch

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/CdcChartComponent.tsx
> +  const prepareConfig = (configObj: ChartConfig) => {
Where are we fetching the configUrl now?

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/CdcChartComponent.tsx
>        setFilteredData(currentData)
dispatch

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/CdcChartComponent.tsx
> -  // Sorts data series for horizontal bar charts
Are you using a different sort fn here?

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/CdcChartComponent.tsx
> -import cacheBustingString from '@cdc/core/helpers/cacheBustingString'
This was used when the response was always loaded from the url to force cache to request a the new config if fifteen minutes had passed. Make sure this stays in place on the fetch.

2025-01-03 19:44 UTC, adamdoe commented on packages/chart/src/CdcChartComponent.tsx
> +import { ChartdDispatchContext } from './ConfigContext'
Spelling

2025-01-03 19:44 UTC, adamdoe commented on packages/dashboard/examples/all-components.json
146K lines is a lot to add into the code base. It looks like there were massive changes to this file or a lot of data added in. Can we remove this or reduce the amount of data in this file?

2025-01-07 13:49 UTC, Atash3000 commented on packages/chart/src/CdcChartComponent.tsx
> +    setConfig(newConfig)
Since setConfig is used everywhere in Core,Filters and all over charts i did this approach  const setConfig = newConfig => {
    dispatch({ type: 'SET_CONFIG', payload: newConfig })
  } so we dont have to update setConfig into   dispatch({ type: 'SET_CONFIG', payload: newConfig }) all over charts or data table

2025-01-07 13:50 UTC, Atash3000 commented on packages/chart/src/CdcChartComponent.tsx
> +        setFilteredData(filteredData)
same here   const setFilteredData = filteredData => {
    dispatch({ type: 'SET_FILTERED_DATA', payload: filteredData })
  }

2025-01-07 13:56 UTC, Atash3000 commented on packages/chart/src/CdcChartComponent.tsx
>        setLoading(false)
Fixed!

2025-01-07 13:56 UTC, Atash3000 commented on packages/chart/src/CdcChartComponent.tsx
> +  console.log(filteredData, 'filteredData')
Fixed!

2025-01-07 13:59 UTC, Atash3000 commented on packages/chart/src/CdcChartComponent.tsx
> -  // Sorts data series for horizontal bar charts
we dont need to sort any bars. it was very old code config.sort  which we dont have logic. also sortings happens now automatically in useScales for time, and date types for vertical bars.Can you re confirm it ?

2025-01-07 14:10 UTC, Atash3000 commented on packages/chart/src/CdcChartComponent.tsx
> +import { ChartdDispatchContext } from './ConfigContext'
Fixed!

2025-01-07 14:10 UTC, Atash3000 commented on packages/chart/src/CdcChartComponent.tsx
> -import cacheBustingString from '@cdc/core/helpers/cacheBustingString'
Fixed!

2025-01-07 14:11 UTC, Atash3000 commented on packages/dashboard/examples/all-components.json
Removed!

2025-01-09 17:05 UTC, closed without merging