DRAFT: Feature/dev 3220 add location to csv
CDCgov/cdc-open-viz pull request #595
Opened 2023-02-22 16:41 UTC by tturnerswdev33

## Briefly describe your changes

## Checklist before requesting a review
- [ ] My pull request was branched from and targets the test branch
- [ ] I have performed a self-review of my code
- [ ] I have manually tested all packages affected (bonus points for automations)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have checked to ensure there aren't other open pull requests for the same change

## Did you test your feature in the following environments?
- [ ] Standalone Component
- [ ] Standalone Full Editor
- [ ] CDC Internal Checks

2023-02-24 21:02 UTC, adamdoe requested changes
### Please see the fixes and nits below
Note: I wasn't able to see the feature working. After fixing the below I'll take another pass on it. Lots of great work here, console.logs being removed, unused icons, etc. Mostly small feedback. Good work!

fix: Don't use hard-coded column names, ie `Fips Codes`
fix: Run prettier. If you can't fix the eslint issues, select the code and run the formatting manually.
fix: try to reduce some of the eslint errors in the file. I know you didn't create these, but we're trying to tackle some of them. This will help code formatting in the future for all devs.

nit: try to scope commits to tickets, not a big deal
nit: out of place comment

2023-02-27 19:34 UTC, tturnerswdev33 commented on packages/chart/src/CdcChart.jsx
> +  // DEV-3218 make "Chart Title" both a required field and default value
Can you elaborate more specifically what you mean?

2023-02-27 19:39 UTC, tturnerswdev33 commented on packages/map/src/components/DataTable.jsx
> +      csvData = Papa.unparse(rawData.map(row => ({ FullGeoName: displayGeoName(row['FIPS Codes']), ...row })))
A you referring to the made up column name "FullGeoName" or are you referring to using 'FIPS Codes'?
In either case not sure what you are asking me to do here... If the latter I dont see another way to get the data...without getting the specific col we need.

2023-02-27 19:41 UTC, tturnerswdev33 commented on packages/map/src/components/DataTable.jsx
> +    let csvData;
Well I only had an if else... until testing showed there was another case that needed to be dealt with.

Yes you could do a switch but that would at a minimum double the lines required to do the exact same thing without much more clarity in my opinion.

2023-02-27 19:46 UTC, tturnerswdev33 commented
@adamdoe I dont see where the eslint issue is.  I have it say to format on save.  Which file are you referring to?

2023-03-01 16:59 UTC, adamdoe commented on packages/map/src/components/DataTable.jsx
> +      csvData = Papa.unparse(rawData.map(row => ({ FullGeoName: displayGeoName(row['FIPS Codes']), ...row })))
Column names are included in the config. Here you don't want to use `Fips Codes`. That's coming from the sample file you loaded. You'll want to browse the config to find where Fips Codes is being pulled from and use that value instead. For example, if you load a county data file and the columns are instead `County Name`, and `County FIps` the row you've hard coded here will never be found. Try looking for `state.columns.geo.name`.

2023-03-01 17:01 UTC, adamdoe commented
@tturnerswdev33 - I ran through feedback here. In addition, if you need to run eslint you can always do that from the command line using `npx eslint [file_pattern]` but your editor should be able to provide the output in the problems tab when running the package.

2023-03-01 17:03 UTC, adamdoe commented
@tturnerswdev33 - Also, when you're ready for this to be re-reviewed click the refresh button near the reviewers name. Thanks!

2023-03-01 17:59 UTC, adamdoe requested changes
I think I forgot to submit the review here. See feedback higher up on the chain.

2023-03-13 14:27 UTC, tturnerswdev33 commented on packages/map/src/components/DataTable.jsx
> +      csvData = Papa.unparse(rawData.map(row => ({ FullGeoName: displayGeoName(row['FIPS Codes']), ...row })))
Yep changed this

2023-03-13 16:37 UTC, adamdoe commented
Breaking in the editor but not component.

2023-03-13 16:37 UTC, adamdoe requested changes
breaking in editor

2023-03-14 17:08 UTC, merged