Force combo charts to always have orientation vertical
CDCgov/cdc-open-viz pull request #608
Opened 2023-02-28 21:40 UTC by tturnerswdev33

## Briefly describe your changes
In the chart EditorPanel file under enforceRestrictions I added an if statement on Combo charts to force orientation = "vertical" because we don't support horizontal right now.  

Previously, If you had a bar chart and set to horizontal then flipped to Combo it would give a janky ugly chart result.

## Checklist before requesting a review
- [ ] My pull request was branched from and targets the test branch
- [ ] I have performed a self-review of my code
- [ ] I have manually tested all packages affected (bonus points for automations)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have checked to ensure there aren't other open pull requests for the same change

## Did you test your feature in the following environments?
- [ ] Standalone Component
- [ ] Standalone Full Editor
- [ ] CDC Internal Checks

2023-03-01 18:20 UTC, adamdoe requested changes
### Review

fix: Did you remember to test your changes? On the example file, I'm able to change the orientation to horizontal. You might also want to hide the orientation setting on Combo charts.

2023-03-01 18:25 UTC, adamdoe approved these changes

2023-03-10 16:07 UTC, adamdoe commented
@tturnerswdev33 -

Is this still in review?

2023-03-11 01:35 UTC, tturnerswdev33 commented
No its good to go if no merge conflicts
 
From: Adam Doe ***@***.***> 
Sent: Friday, March 10, 2023 11:08 AM
To: CDCgov/cdc-open-viz ***@***.***>
Cc: Tim Turner ***@***.***>; Mention ***@***.***>
Subject: Re: [CDCgov/cdc-open-viz] DEV-3293 - Force combo charts to always have orientation vertical (PR #608)
 
@tturnerswdev33 <https://github.com/tturnerswdev33>  -
Is this still in review?
—
Reply to this email directly, view it on GitHub <https://github.com/CDCgov/cdc-open-viz/pull/608#issuecomment-1464031294> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/A5FDQ54BRULURW3YRPE6VMDW3NGVJANCNFSM6AAAAAAVLII5AM> .
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-03-13 15:49 UTC, merged