Feature/dev 3218 and 3221 new merge version
CDCgov/cdc-open-viz pull request #624
Opened 2023-03-15 22:42 UTC by tturnerswdev33

## Briefly describe your changes
uoved 
DEV-3218 on map and charts the Title needs to always have a value even if they delete it out of the text box entirely.  Also added a SHOW TITLE checkbox that lets them hide the title.

DEV-3221 makes the Data Table Title also required so that if they delete it out entirely it will still set it to 'Data Table'.  Also moved the Show Data Table checkbox up by that to be consistent in the interface

## Checklist before requesting a review
- [ ] My pull request was branched from and targets the test branch
- [ ] I have performed a self-review of my code
- [ ] I have manually tested all packages affected (bonus points for automations)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have checked to ensure there aren't other open pull requests for the same change

## Did you test your feature in the following environments?
- [ ] Standalone Component
- [ ] Standalone Full Editor
- [ ] CDC Internal Checks

2023-03-17 19:06 UTC, adamdoe requested changes
fix: see feedback related to default chart / map titles. Happy to go over on a call if needed.

2023-03-17 19:06 UTC, adamdoe commented on packages/map/src/components/EditorPanel.jsx
> +                                        <label className='checkbox'>
Looks like prettier made an oops here.

2023-03-17 22:16 UTC, tturnerswdev33 commented on packages/chart/src/components/EditorPanel.jsx
> +    if ('table' === section && null === subsection) {
Used even simpler method that we went over on the call. DOH!

2023-03-18 01:22 UTC, adamdoe approved these changes

2023-03-18 01:23 UTC, merged